// modules/react/src/App.js
import React, { useState } from 'react';
import { AgGridReact } from '@ag-grid-community/react';

import { ModuleRegistry } from '@ag-grid-community/core';

import { ClientSideRowModelModule } from "@ag-grid-community/client-side-row-model";
import { StatusBarModule } from "@ag-grid-enterprise/status-bar";
import '@ag-grid-community/styles/ag-grid.css';
import '@ag-grid-community/styles/ag-theme-alpine.css';

ModuleRegistry.register(ClientSideRowModelModule);
ModuleRegistry.register(StatusBarModule);

const App = () => {
  const [rowData] = useState([
    {make: "Toyota", model: "Celica", price: 35000},
    {make: "Ford", model: "Mondeo", price: 32000},
    {make: "Porsche", model: "Boxster", price: 72000}
  ]);

  const [columnDefs] = useState([
    { field: 'make' },
    { field: 'model' },
    { field: 'price' }
  ])

  return (
      <div className="ag-theme-alpine" style={{height: 400, width: 600}}>
        <AgGridReact
            rowData={rowData}
            columnDefs={columnDefs}>
        </AgGridReact>
      </div>
  );
};


export default App;

// modules/angular-community/src/app/app.component.ts
import { Component } from '@angular/core';
import { ColDef, ModuleRegistry } from '@ag-grid-community/core';

import { ClientSideRowModelModule } from "@ag-grid-community/client-side-row-model";

ModuleRegistry.register(ClientSideRowModelModule);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.scss' ]
})
export class AppComponent  {

  columnDefs: ColDef[] = [
    { field: 'make' },
    { field: 'model' },
    { field: 'price' }
  ];

  rowData = [
    { make: 'Toyota', model: 'Celica', price: 35000 },
    { make: 'Ford', model: 'Mondeo', price: 32000 },
    { make: 'Porsche', model: 'Boxster', price: 72000 }
  ];
}

<ag-grid-angular
  [columnDefs]="columnDefs"
  [rowData]="rowData"
  class="ag-theme-alpine"
  style="width: 500px; height: 350px;">
</ag-grid-angular>
